#!/bin/bash

# This script monitors the audio input for non-silence and automatically starts recording.
# It will run continuously until stopped.
# See http://sox.sourceforge.net/sox.html for more options.

# tunable parameters
WORKINGDIR="/home/incognitus/RECS/"
STARTIDFILE="startid"
SOXDIR="/usr/bin"
STOPFILE="stoprecording"

# no logging yet
LOGFILE="output.log"
VERBOSITY="0"

FILENAME_PREFIX="REC0"
OUTPUT_FORMAT="flac"
MIN_DURATION="0" # delete recordings shorter than this many minutes

# see the sox man page for the silence plugin
ABOVE_PERIODS="1 0.50 0.1%"
BELOW_PERIODS="2 00:03 0.1%"

tag ()
{
  flac -s -f -T "Album=REC Sessions" -T "URL=http://radio.beats.to" -T "Recorded=`date`" $1
}

# let's go
echo `date` "Starting up." 
cd $WORKINGDIR

# Loop until somebody creates $STOPFILE
while [ ! -f $STOPFILE ] ;  do

  # Prepare the file name
  REC_ID=`head -1 $STARTIDFILE`
  CURRENT_FILE=$FILENAME_PREFIX$REC_ID.$OUTPUT_FORMAT
  
  echo "Waiting for audio stream to start.  Will record ($CURRENT_FILE)." 
  $SOXDIR/rec  $CURRENT_FILE silence $ABOVE_PERIODS $BELOW_PERIODS

  # Check the duration of the recording is longer than $MIN_DURATION.  This helps 
  # avoid crap such as pops when equipment is turned on.
  if [ $MIN_DURATION != 0 ]; then

    REC_DURATION=`$SOXDIR/soxi -d $CURRENT_FILE`
    REC_HOURS=`echo $REC_DURATION | cut -d: -f1`
    REC_MINUTES=`echo $REC_DURATION | cut -d: -f2`

    if [ $REC_HOURS = "00" ] && [ $REC_MINUTES -lt $MIN_DURATION ]; then
    echo "Recording discarded; too short ($REC_DURATION)" 
    rm -f $CURRENT_FILE
  else
    echo "Keeping $CURRENT_FILE ($REC_DURATION)."
    tag $CURRENT_FILE
    # increment the ID
    echo $REC_ID " + 1" | bc > $STARTIDFILE
  fi

done
